
export const ADD_TODO = 'ADD_TODO';

export const FILTER_TODOS_SHARE = 'FILTER_TODOS_SHARE';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const ADD_TODOS_SHARE = 'ADD_TODOS_SHARE';

export const CHANGE_TODO = 'CHANGE_TODO';

